### ISSUE TITLE
Pacote Service

### ISSUE THREAD

**Issue by rodrigondec** [danielsmithm/Home-Control#10]
Nós temos _HomeControl.Service_ que tem a classe  **ResidenciaService** e nós temos o _HomeControl.Business.Service.implementation_ com **ResidenciaService**, **InterruptorService** e **ComodoService**.

Onde ficarão os services?

**Comment by danielsmithm** [comment]
Esse projeto existe no git, mas na solução não é mostrado. Remover manualente.

**Comment by rodrigondec** [comment]
remover o _HomeControl.Service_  no caso então né?

**Comment by danielsmithm** [comment]
Sim.
