### ISSUE TITLE
Pasta implementation, Implementation e Implementations

### ISSUE THREAD

**Issue by rodrigondec** [danielsmithm/Home-Control#11]
Nós temos as pastas: 
_Home-Control/HomeControl.Data/Dal/Dao/Custom/**Implementations**/
Home-Control/HomeControl.Business/Service/**implementation**/
Home-Control/HomeControl.Business/Service/**Implementation**/_

Como vai ser o modelo de projeto? pasta com nome "**implementation**", "**Implementation**" ou "**Implementations**"??

**Comment by danielsmithm** [comment]
Implementations
