### ISSUE TITLE
Classes DalConfiguration e DalException

### ISSUE THREAD

**Issue by rodrigondec** [danielsmithm/Home-Control#12]
A classe **DalConfiguration** está no pacote _HomeControl.Business_.Service.Configuration.
Enquanto a classe **DalException** está no pacote _HomeControl.Data_.Dal.Exceptions.

![image](https://cloud.githubusercontent.com/assets/3301060/24372409/42a3ccca-1304-11e7-9768-b64893eefeb1.png)

Essas classes deveriam estar no mesmo pacote não?

**Comment by danielsmithm** [comment]
Não acredito que precise mudar o pacote das classes. DalConfiguration diz respeito à configuração do uso da camada de dados pela camada de serviço.
