### ISSUE TITLE
Erro"An exception of type 'System.InvalidOperationException' occurred"

### ISSUE THREAD

**Issue by rodrigondec** [danielsmithm/Home-Control#16]
tentei dar build com o push (Correção do update em AbstractDao. a95efc4fa1e16aed656687d589e83b47999a2306) que vc fez e deu esse erro. 

Wesley disse que era a criação do localdb que tava dando problema. 

Alterei o nome do source do localdb utilizado no arquivo App.config porém continou dando o mesmo erro

![image](https://cloud.githubusercontent.com/assets/3301060/24582119/24a4304e-16ff-11e7-8d34-d9e968415e0f.png)

**Comment by danielsmithm** [comment]
Este problema ocorre ao tentar executar a aplicação com migrações ainda não efetuadas. O procedimento para resolver o problema é: No Package Manager Console, executar o comando "Updtate-Database". Após executar as migrações serão aplicadas.
