### ISSUE TITLE
CRUD  Residência

### ISSUE THREAD

**Issue by danielsmithm** [danielsmithm/Home-Control#6]
Fazer a implementação do Crud Para Residência.

Tarefas: 

- [x] Fazer ResidenciaService

- [x] Validações no ResidenciaService

- [x] Métodos no ResidenciaController

- [x] Método delete no ResidenciaController

- [x] Páginas de view para os métodos do ResidenciaController

**Comment by danielsmithm** [comment]
Implementado cadastro e listagem de residências.

**Comment by rodrigondec** [comment]
edit e details feito

**Comment by rodrigondec** [comment]
Fazer a implementação do Crud Para Residência.

Tarefas: 

- [ ] Validações no ResidenciaService

- [ ] Métodos no ResidenciaController

- [ ] Método delete no ResidenciaController

- [ ] Páginas de view para os métodos do ResidenciaController
