### ISSUE TITLE
Nome de interface do Knob/Potenciometro

### ISSUE THREAD

**Issue by rodrigondec** [danielsmithm/Home-Control#9]
Interfaces possuem o nome começando com "I". 

![image](https://cloud.githubusercontent.com/assets/3301060/24371809/693634f6-1302-11e7-9289-dde4fe93e12d.png)

O nome da interface da interface do Knob no _HomeControl.Domain.Domain.Knob_ está como **Knob** e não **IKnob**. Como será o padrão?

**Comment by danielsmithm** [comment]
IKnob.
